/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Goal_Setting;
import User_Authentication.Cookies;
import User_Authentication.DataBase;
import com.formdev.flatlaf.FlatLightLaf;
import com.mycompany.personal_finance_management_system.Menu_Page;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.border.Border;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author Mohamed Ahmed
 */
public class Goal_Planner extends javax.swing.JFrame {
    /**
     * Creates new form Goal_Planner
     * @throws java.sql.SQLException
     */
    public Goal_Planner() throws SQLException {
        //retreive the data from database
        GoalDBCreator.Connection();
        //unselect every row in jTable 2 when starting a new object
        rowIndex = -1;
        initComponents();
        total = (int) (DataBase.getTotalIncome_db(Cookies.getID())-DataBase.getTotalExpense_db(Cookies.getID()));
        if(total < 0)
            total = 0;
        System.out.println("total = "+total);
    }
    //Total amount of saved money
    private int total;
    //target amount and date selected from jTable3
    private int targetAmount;
    private String selectedDate;
    //Text limiter variable for the discreption JTextArea
    private final int charLimit = 200;
    //jTable2 Data selected when clicking on a row
    private String value1, value2, value3, value4, value5;
    private int rowIndex;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        Back_Button = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Back_Tab = new javax.swing.JPanel();
        Goal_Planner = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser(new Date());
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        charCountLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Save_Button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Edit_Goals = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jDateChooser2 = new com.toedter.calendar.JDateChooser(new Date());
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        charCountLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Update_Button = new javax.swing.JButton();
        Delete_Button = new javax.swing.JButton();
        Progress_Viewer = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jPanel5.setMinimumSize(new java.awt.Dimension(75, 30));
        jPanel5.setLayout(new java.awt.BorderLayout());

        Back_Button.setFont(Back_Button.getFont().deriveFont(Back_Button.getFont().getStyle() | java.awt.Font.BOLD, 16));
        Back_Button.setText("🢀 Back");
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });
        jPanel5.add(Back_Button, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Goal Setting");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout Back_TabLayout = new javax.swing.GroupLayout(Back_Tab);
        Back_Tab.setLayout(Back_TabLayout);
        Back_TabLayout.setHorizontalGroup(
            Back_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );
        Back_TabLayout.setVerticalGroup(
            Back_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab4", Back_Tab);

        jDateChooser1.setDateFormatString("dd/MM/yyyy");
        jDateChooser1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jDateChooser1.setMinSelectableDate(new Date());
        JTextFieldDateEditor editor = (JTextFieldDateEditor) jDateChooser1.getDateEditor();
        editor.setEditable(false);
        editor.setFocusable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Deadline:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Goal Name:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Goal Category:");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Emergency Fund", "Debt Repayment", "Retirement Savings", "Vacation Fund", "Building wealth", "Down Payment Savings" }));
        jComboBox1.setEditable(true);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Target Amount:");

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Description");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);
        jTextArea1.setLineWrap(true);

        jTextArea1.setWrapStyleWord(true);

        // set the maximum length of the text area
        jTextArea1.setDocument(new JText_limiter(charLimit));

        jTextArea1.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateCharCount();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateCharCount();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateCharCount();
            }

            private void updateCharCount() {
                int charCount = jTextArea1.getText().length();
                charCountLabel.setText(charCount + "/" + charLimit);
            }
        });

        charCountLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        charCountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        charCountLabel.setText("0/" + charLimit);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Character Count:");

        Save_Button.setFont(Save_Button.getFont().deriveFont(Save_Button.getFont().getStyle() | java.awt.Font.BOLD, 16));
        Save_Button.setIcon(new javax.swing.ImageIcon("icons/icons8-save-48.png"));
        Save_Button.setText("Save");
        Save_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_ButtonActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable1.setModel(GoalDBCreator.model);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setEnabled(false);
        jScrollPane2.setViewportView(jTable1);
        // Enable sorting
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(jTable1.getModel());
        jTable1.setRowSorter(sorter);
        DialogCellRenderer.Tooltip_setter(jTable1);

        javax.swing.GroupLayout Goal_PlannerLayout = new javax.swing.GroupLayout(Goal_Planner);
        Goal_Planner.setLayout(Goal_PlannerLayout);
        Goal_PlannerLayout.setHorizontalGroup(
            Goal_PlannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Goal_PlannerLayout.createSequentialGroup()
                .addGroup(Goal_PlannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Goal_PlannerLayout.createSequentialGroup()
                        .addContainerGap(14, Short.MAX_VALUE)
                        .addGroup(Goal_PlannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Goal_PlannerLayout.createSequentialGroup()
                                .addGroup(Goal_PlannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(16, 16, 16)
                                .addGroup(Goal_PlannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Goal_PlannerLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(Goal_PlannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(175, 175, 175)
                                .addComponent(jLabel6)
                                .addGap(6, 6, 6)
                                .addComponent(charCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Goal_PlannerLayout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addGroup(Goal_PlannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Goal_PlannerLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(Goal_PlannerLayout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(Save_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Goal_PlannerLayout.setVerticalGroup(
            Goal_PlannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Goal_PlannerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(Goal_PlannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Goal_PlannerLayout.createSequentialGroup()
                        .addGroup(Goal_PlannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGroup(Goal_PlannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Goal_PlannerLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(Goal_PlannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addGroup(Goal_PlannerLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Goal_PlannerLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(Goal_PlannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))))
                .addGap(9, 9, 9)
                .addGroup(Goal_PlannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(charCountLabel))
                .addGap(2, 2, 2)
                .addComponent(Save_Button)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Goal Planner", Goal_Planner);

        jTable2.setModel(GoalDBCreator.model);
        jScrollPane3.setViewportView(jTable2);
        DialogCellRenderer.Tooltip_setter(jTable2);
        jTable2.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                rowIndex = jTable2.getSelectedRow();
                if (rowIndex != -1) { // Make sure a row is selected
                    value1 = jTable2.getValueAt(rowIndex, 0).toString(); // Assuming the value you want is in the first column
                    value2 = jTable2.getValueAt(rowIndex, 1).toString(); // Assuming the value you want is in the second column
                    value3 = jTable2.getValueAt(rowIndex, 2).toString(); // Assuming the value you want is in the third column
                    value4 = jTable2.getValueAt(rowIndex, 3).toString(); // Assuming the value you want is in the second column
                    value5 = jTable2.getValueAt(rowIndex, 4).toString(); // Assuming the value you want is in the third column

                    // Set the value of the selected row into the corresponding JTextFields
                    jTextField3.setText(value1);
                    jComboBox2.setSelectedItem(value2);
                    jTextField4.setText(value3);
                    //Convert date to Date object
                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                    Date date = null;
                    try {
                        date = dateFormat.parse(value4);
                    } catch (ParseException e) {
                        System.out.println("Date conversion error");
                    }
                    jDateChooser2.setDate(date);
                    jTextArea2.setText(value5);
                }
            }
        });
        //Enable sorting
        TableRowSorter<TableModel> sorter1 = new TableRowSorter<TableModel>(jTable2.getModel());
        jTable2.setRowSorter(sorter1);
        jTable2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        jDateChooser2.setDateFormatString("dd/MM/yyyy");
        jDateChooser2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jDateChooser2.setMinSelectableDate(new Date());
        JTextFieldDateEditor editor2 = (JTextFieldDateEditor) jDateChooser2.getDateEditor();
        editor2.setEditable(false);
        editor2.setFocusable(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Deadline:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Goal Category:");

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Emergency Fund", "Debt Repayment", "Retirement Savings", "Vacation Fund", "Building wealth", "Down Payment Savings" }));
        jComboBox2.setEditable(true);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Goal Name:");

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Target Amount:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Description");

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);
        jTextArea2.setLineWrap(true);

        jTextArea2.setWrapStyleWord(true);

        // set the maximum length of the text area
        jTextArea2.setDocument(new JText_limiter(charLimit));

        jTextArea2.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateCharCount();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateCharCount();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateCharCount();
            }

            private void updateCharCount() {
                int charCount = jTextArea2.getText().length();
                charCountLabel1.setText(charCount + "/" + charLimit);
            }
        });

        charCountLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        charCountLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        charCountLabel1.setText("0/" + charLimit);
        charCountLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Character Count:");

        Update_Button.setFont(Update_Button.getFont().deriveFont(Update_Button.getFont().getStyle() | java.awt.Font.BOLD, 16));
        Update_Button.setIcon(new javax.swing.ImageIcon("icons/icons8-update-48.png"));
        Update_Button.setText("Update");
        Update_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_ButtonActionPerformed(evt);
            }
        });

        Delete_Button.setFont(Delete_Button.getFont().deriveFont(Delete_Button.getFont().getStyle() | java.awt.Font.BOLD, 16));
        Delete_Button.setIcon(new javax.swing.ImageIcon("icons/icons8-cross-mark-48.png"));
        Delete_Button.setText("Delete");
        Delete_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Edit_GoalsLayout = new javax.swing.GroupLayout(Edit_Goals);
        Edit_Goals.setLayout(Edit_GoalsLayout);
        Edit_GoalsLayout.setHorizontalGroup(
            Edit_GoalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Edit_GoalsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Edit_GoalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(9, 9, 9)
                .addGroup(Edit_GoalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Edit_GoalsLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(Edit_GoalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField4)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(Edit_GoalsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Edit_GoalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Edit_GoalsLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Edit_GoalsLayout.createSequentialGroup()
                        .addGroup(Edit_GoalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Edit_GoalsLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(6, 6, 6)
                                .addComponent(charCountLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Update_Button)
                        .addGap(30, 30, 30)
                        .addComponent(Delete_Button)
                        .addGap(31, 31, 31))))
        );
        Edit_GoalsLayout.setVerticalGroup(
            Edit_GoalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Edit_GoalsLayout.createSequentialGroup()
                .addGroup(Edit_GoalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Edit_GoalsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Edit_GoalsLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(Edit_GoalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Edit_GoalsLayout.createSequentialGroup()
                                .addGroup(Edit_GoalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(36, 36, 36)
                                .addGroup(Edit_GoalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addGroup(Edit_GoalsLayout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addGroup(Edit_GoalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(27, 27, 27)
                        .addGroup(Edit_GoalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGroup(Edit_GoalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Edit_GoalsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Edit_GoalsLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(Edit_GoalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Update_Button)
                            .addComponent(Delete_Button))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Edit_GoalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(charCountLabel1))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Edit Goals", Edit_Goals);

        jTable3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable3.setModel(GoalDBCreator.model);
        jTable3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane5.setViewportView(jTable3);
        DialogCellRenderer.Tooltip_setter(jTable3);
        jTable3.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                rowIndex = jTable3.getSelectedRow();
                String style1 = "<html><font color='green' size='6'>&bull;</font> In Progress</html>";
                String style2 = "<html><font color='green' size='6'>&bull;</font> Complete</html>";
                String style3 = "<html><font color='red' size='6'>&bull;</font> Past Due</html>";
                if (rowIndex != -1){// Make sure a row is selected
                    selectedDate = jTable3.getValueAt(rowIndex, 3).toString();
                    targetAmount = Integer.parseInt(jTable3.getValueAt(rowIndex, 2).toString()); // get the String value of the target amount
                    //selecting column's valuses to prepare for Complete button actionperforme
                    value1 = jTable3.getValueAt(rowIndex, 0).toString();
                    value2 = jTable3.getValueAt(rowIndex, 1).toString();
                    value3 = jTable3.getValueAt(rowIndex, 2).toString();
                    value4 = jTable3.getValueAt(rowIndex, 3).toString();
                    value5 = jTable3.getValueAt(rowIndex, 4).toString();
                }
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                Date date = null;
                try {
                    date = dateFormat.parse(selectedDate);
                } catch (ParseException e) {
                    System.out.println("Date conversion error");
                }
                boolean pastDue = DateComparator.is_pastdue(date);
                jProgressBar1.setMaximum(targetAmount);
                jProgressBar1.setValue(total);
                jProgressBar1.setStringPainted(true);
                if(total >= targetAmount){
                    jButton1.setEnabled(true);
                    jProgressBar1.setString("100%");
                    jLabel15.setText(style2);
                    if(pastDue == true)
                    jLabel15.setText(style3);
                }

                else{
                    jButton1.setEnabled(false);
                    jProgressBar1.setString((double)total/targetAmount+"%");
                    if(pastDue == true)
                    jLabel15.setText(style3);
                    else
                    jLabel15.setText(style1);
                }
            }});
            //Enable sorting
            TableRowSorter<TableModel> sorter2 = new TableRowSorter<TableModel>(jTable3.getModel());
            jTable3.setRowSorter(sorter2);
            jTable3.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

            jProgressBar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            jProgressBar1.setForeground(new java.awt.Color(1, 35, 69));

            jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jLabel13.setText("Progress:");

            jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jLabel14.setText("Status:");

            jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jLabel15.setText(" ");

            jButton1.setFont(jButton1.getFont().deriveFont(jButton1.getFont().getStyle() | java.awt.Font.BOLD, jButton1.getFont().getSize()+4));
            jButton1.setIcon(new javax.swing.ImageIcon("icons/icons8-done-48.png"));
            jButton1.setText("Complete");
            jButton1.setEnabled(false);
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout Progress_ViewerLayout = new javax.swing.GroupLayout(Progress_Viewer);
            Progress_Viewer.setLayout(Progress_ViewerLayout);
            Progress_ViewerLayout.setHorizontalGroup(
                Progress_ViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Progress_ViewerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(Progress_ViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane5)
                        .addGroup(Progress_ViewerLayout.createSequentialGroup()
                            .addGroup(Progress_ViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(Progress_ViewerLayout.createSequentialGroup()
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(353, 353, 353))
                                .addGroup(Progress_ViewerLayout.createSequentialGroup()
                                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(91, 91, 91)))
                            .addGroup(Progress_ViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(Progress_ViewerLayout.createSequentialGroup()
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(29, 29, 29))
                                .addGroup(Progress_ViewerLayout.createSequentialGroup()
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addGap(92, 92, 92)))))
                    .addContainerGap())
            );
            Progress_ViewerLayout.setVerticalGroup(
                Progress_ViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Progress_ViewerLayout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(Progress_ViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Progress_ViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(60, 60, 60))
            );

            jTabbedPane1.addTab("Progress Viewer", Progress_Viewer);

            jTable4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            jTable4.setModel(GoalDBCreator.compModel);
            jTable4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            jScrollPane6.setViewportView(jTable4);
            DialogCellRenderer.Tooltip_setter(jTable4);
            jTable4.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent event) {
                    rowIndex = jTable4.getSelectedRow();
                    if (rowIndex != -1){// Make sure a row is selected
                        //selecting column's valuses to prepare for Complete button actionperforme
                        value1 = jTable4.getValueAt(rowIndex, 0).toString();
                        value2 = jTable4.getValueAt(rowIndex, 1).toString();
                        value3 = jTable4.getValueAt(rowIndex, 2).toString();
                        value4 = jTable4.getValueAt(rowIndex, 3).toString();
                    }
                }});
                //Enable sorting
                TableRowSorter<TableModel> sorter3 = new TableRowSorter<TableModel>(jTable4.getModel());
                jTable4.setRowSorter(sorter3);
                jTable4.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

                jButton2.setFont(jButton2.getFont().deriveFont(jButton2.getFont().getStyle() | java.awt.Font.BOLD, jButton2.getFont().getSize()+4));
                jButton2.setIcon(new javax.swing.ImageIcon("icons/icons8-cross-mark-48.png"));
                jButton2.setText("Delete");
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton2ActionPerformed(evt);
                    }
                });

                jButton3.setFont(jButton3.getFont().deriveFont(jButton3.getFont().getStyle() | java.awt.Font.BOLD, jButton3.getFont().getSize()+4));
                jButton3.setIcon(new javax.swing.ImageIcon("icons/icons8-trash-48.png"));
                jButton3.setText("Clear All");
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton3ActionPerformed(evt);
                    }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(104, 104, 104)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(75, 75, 75))
                );
                jPanel1Layout.setVerticalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72))
                );

                jTabbedPane1.addTab("Completed Goals", jPanel1);

                jTabbedPane1.setSelectedIndex(1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                );

                jTabbedPane1.setTabComponentAt(0, jPanel5);
                jTabbedPane1.setEnabledAt(0, false);

                setSize(new java.awt.Dimension(716, 467));
                setLocationRelativeTo(null);
            }// </editor-fold>//GEN-END:initComponents

    private void Save_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_ButtonActionPerformed
        boolean valid = true;
        //new border for invalid inputs
        Border border = BorderFactory.createLineBorder(Color.RED, 2, true);
        if(Check_Input.checkEmpty(jTextField1.getText())){
            valid = false;
            jTextField1.setBorder(border);
            jTextField1.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                jTextField1.setBorder(new JTextField().getBorder());
            }});
        }
                    
        if(Check_Input.checkEmpty((String) jComboBox1.getSelectedItem())){
            valid = false;
            jComboBox1.setBorder(border);
            jComboBox1.setEditable(false);
            jComboBox1.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                    jComboBox1.setBorder(new JComboBox<String>().getBorder());
                    jComboBox1.setEditable(true);
            }});
        }
        
        if (Check_Input.checkNumeric(jTextField2.getText())){
            valid = false;
            jTextField2.setBorder(border);
            jTextField2.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                jTextField2.setBorder(new JTextField().getBorder());
            }});
        }
        if(!valid)
            JOptionPane.showMessageDialog(null, "Invalid Input", "Warning", JOptionPane.ERROR_MESSAGE);
        else{
            Date javaDate = jDateChooser1.getDate();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String Date = dateFormat.format(javaDate);
            //insert data to the database and jTable
            GoalDBCreator.Insert_Data(
                    GoalDBCreator.id,
                    jTextField1.getText(),
                    String.valueOf(jComboBox1.getSelectedItem()),
                    jTextField2.getText(),
                    Date,
                    jTextArea1.getText());
            //add new row to Table model
            GoalDBCreator.model.addRow( new Object[]{
                                        jTextField1.getText(),
                                        String.valueOf(jComboBox1.getSelectedItem()),
                                        jTextField2.getText(),
                                        Date,
                                        jTextArea1.getText()});
            //notify the jTable with the changes made in the Table model
            GoalDBCreator.model.fireTableDataChanged();
            //reset the feilds after Save process
            Reset_Components.Reset_feilds(jTextField1, jTextField2, jTextArea1, jComboBox1, jDateChooser1);
        }
            
    }//GEN-LAST:event_Save_ButtonActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed
        Menu_Page obj = new Menu_Page();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Back_ButtonActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void Update_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_ButtonActionPerformed
        //Checks if there is a row selected or not
        System.out.println("row index = "+rowIndex);
        if(rowIndex != -1){
            boolean valid = true;
            //new border for invalid inputs
            Border border = BorderFactory.createLineBorder(Color.RED, 2);

            if(Check_Input.checkEmpty(jTextField3.getText())){
                valid = false;
                jTextField3.setBorder(border);
                jTextField3.addFocusListener(new FocusAdapter() {
                @Override
                public void focusGained(FocusEvent e) {
                    jTextField3.setBorder(new JTextField().getBorder());
                }});
            }

            if(Check_Input.checkEmpty((String) jComboBox2.getSelectedItem())){
                valid = false;
                jComboBox2.setBorder(border);
                jComboBox2.setEditable(false);
                jComboBox2.addFocusListener(new FocusAdapter() {
                @Override
                public void focusGained(FocusEvent e) {
                        jComboBox2.setBorder(new JComboBox<String>().getBorder());
                        jComboBox2.setEditable(true);
                }});
            }

            if (Check_Input.checkNumeric(jTextField4.getText())){
                valid = false;
                jTextField4.setBorder(border);
                jTextField4.addFocusListener(new FocusAdapter() {
                @Override
                public void focusGained(FocusEvent e) {
                    jTextField4.setBorder(new JTextField().getBorder());
                }});
            }
            if(!valid)
                JOptionPane.showMessageDialog(null, "Invalid Input", "Warning", JOptionPane.ERROR_MESSAGE);
            else{
                Date javaDate = jDateChooser2.getDate();
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                String Date = dateFormat.format(javaDate);
                //Update data and save it to the database and jTable
                GoalDBCreator.Update_Data(
                        GoalDBCreator.id,
                        value1,
                        value2,
                        value3,
                        value4,
                        value5,
                        jTextField3.getText(),
                        String.valueOf(jComboBox2.getSelectedItem()),
                        jTextField4.getText(),
                        Date,
                        jTextArea2.getText());
                // Set the new data for the row in the table model.
                GoalDBCreator.model.setValueAt(jTextField3.getText(), rowIndex, 0);
                GoalDBCreator.model.setValueAt(String.valueOf(jComboBox2.getSelectedItem()), rowIndex, 1);
                GoalDBCreator.model.setValueAt(jTextField4.getText(), rowIndex, 2);
                GoalDBCreator.model.setValueAt(Date, rowIndex, 3);
                GoalDBCreator.model.setValueAt(jTextArea2.getText(), rowIndex, 4);
                // Call the fireTableDataChanged() method to notify the JTable with the data that has changed.
                GoalDBCreator.model.fireTableDataChanged();
                //reset the feilds after Update process
                Reset_Components.Reset_feilds(jTextField3, jTextField4, jTextArea2, jComboBox2, jDateChooser2);
                }
        }
        else
            //show an error if User hasn't select any row before clicking Update jButton
            JOptionPane.showMessageDialog(null, "No Data has been selected", "Warning", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_Update_ButtonActionPerformed

    private void Delete_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_ButtonActionPerformed
        if(rowIndex != -1)
        {
            //Array of jButtons
            JButton[] buttons = {
            new JButton("Yes"),
            new JButton("No"),
            };
            // Set the style of the buttons
            for (JButton button : buttons) {
                button.setFont(new Font("Arial", Font.BOLD, 14));
            }
            // Show a JOptionPane with custom buttons
            int result = JOptionPane.showConfirmDialog (null, "Do you want to Delete this row", "Confirm", JOptionPane.YES_NO_OPTION);
            //Actions performed based on User's choice
            if (result == JOptionPane.YES_OPTION) {
                GoalDBCreator.model.removeRow(rowIndex);
                GoalDBCreator.model.fireTableDataChanged();
                Date javaDate = jDateChooser2.getDate();
                //reset the feilds after Deletion process
                Reset_Components.Reset_feilds(jTextField3, jTextField4, jTextArea2, jComboBox2, jDateChooser2);
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                String Date = dateFormat.format(javaDate);
                GoalDBCreator.Delete_Data(
                            GoalDBCreator.id,
                            value1,
                            value2,
                            value3,
                            value4,
                            value5);
                }
            else if (result == JOptionPane.NO_OPTION){}
        }
        else
            JOptionPane.showMessageDialog(null, "No Data has been selected", "Warning", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_Delete_ButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(rowIndex != -1)
        {
            // Show a JOptionPane with custom buttons
            int result = JOptionPane.showConfirmDialog (null, "Do you want to Complete this goal", "Confirmation Question", JOptionPane.YES_NO_OPTION);
            //Actions performed based on User's choice
            if (result == JOptionPane.YES_OPTION) {
                GoalDBCreator.model.removeRow(rowIndex);
                GoalDBCreator.model.fireTableDataChanged();
                Object[] row = {value1,value2,value3,value4};
                GoalDBCreator.compModel.addRow(row);
                GoalDBCreator.compModel.fireTableDataChanged();
                GoalDBCreator.Complete_Data(
                        GoalDBCreator.id,
                        value1,
                        value2,
                        value3,
                        value4,
                        value5);
                //remove the goal's amount from the total net amount
                total -= targetAmount;
                }
            else if (result == JOptionPane.NO_OPTION){}
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        GoalDBCreator.DeleteComp_Data(
                            GoalDBCreator.id,
                            value1,
                            value2,
                            value3,
                            value4);
        GoalDBCreator.compModel.removeRow(rowIndex);
        GoalDBCreator.compModel.fireTableDataChanged();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        GoalDBCreator.ClearComp_Data(GoalDBCreator.id);
        int rowCount = GoalDBCreator.compModel.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
        GoalDBCreator.compModel.removeRow(i);
        }
        GoalDBCreator.compModel.fireTableDataChanged();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Goal_Planner().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(Goal_Planner.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Button;
    private javax.swing.JPanel Back_Tab;
    private javax.swing.JButton Delete_Button;
    private javax.swing.JPanel Edit_Goals;
    private javax.swing.JPanel Goal_Planner;
    private javax.swing.JPanel Progress_Viewer;
    private javax.swing.JButton Save_Button;
    private javax.swing.JButton Update_Button;
    private javax.swing.JLabel charCountLabel;
    private javax.swing.JLabel charCountLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private static javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
